/**
 * Cities / towns for heritage locations (Sri Lanka).
 * Edit this list anytime — the admin location form uses it as the dropdown source.
 */
export const SRI_LANKA_CITIES = [
  'Ampara',
  'Anuradhapura',
  'Badulla',
  'Batticaloa',
  'Bentota',
  'Chilaw',
  'Colombo',
  'Dambulla',
  'Ella',
  'Galle',
  'Gampaha',
  'Hambantota',
  'Hatton',
  'Jaffna',
  'Kalutara',
  'Kandy',
  'Kegalle',
  'Kilinochchi',
  'Kurunegala',
  'Mannar',
  'Matale',
  'Matara',
  'Mirissa',
  'Monaragala',
  'Moratuwa',
  'Negombo',
  'Nuwara Eliya',
  'Panadura',
  'Point Pedro',
  'Polonnaruwa',
  'Puttalam',
  'Ratnapura',
  'Sigiriya',
  'Trincomalee',
  'Vavuniya',
  'Wattala',
  'Welimada',
].sort((a, b) => a.localeCompare(b));
