/// Cities shown in the app location picker.
/// Keep aligned with [admin_panel/src/constants/sriLankaCities.js] when you change the list.
const List<String> kSriLankaCities = [
  'Ampara',
  'Anuradhapura',
  'Badulla',
  'Batticaloa',
  'Bentota',
  'Chilaw',
  'Colombo',
  'Dambulla',
  'Ella',
  'Galle',
  'Gampaha',
  'Hambantota',
  'Hatton',
  'Jaffna',
  'Kalutara',
  'Kandy',
  'Kegalle',
  'Kilinochchi',
  'Kurunegala',
  'Mannar',
  'Matale',
  'Matara',
  'Mirissa',
  'Monaragala',
  'Moratuwa',
  'Negombo',
  'Nuwara Eliya',
  'Panadura',
  'Point Pedro',
  'Polonnaruwa',
  'Puttalam',
  'Ratnapura',
  'Sigiriya',
  'Trincomalee',
  'Vavuniya',
  'Wattala',
  'Welimada',
];
