// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSILscLjTFgsPYNoTNOddcvOqqQttEgPY',
    appId: '1:339553065196:web:83d9a730093aa521156dc9',
    messagingSenderId: '339553065196',
    projectId: 'ceylon-trails-bec69',
    authDomain: 'ceylon-trails-bec69.firebaseapp.com',
    storageBucket: 'ceylon-trails-bec69.firebasestorage.app',
    measurementId: 'G-VWZWH4N5WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMQ9P2hiykEMgdfPnDKzw1FqkH-rdY0yk',
    appId: '1:339553065196:android:acd218d216649b25156dc9',
    messagingSenderId: '339553065196',
    projectId: 'ceylon-trails-bec69',
    storageBucket: 'ceylon-trails-bec69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpuwgmrgmn6Ib8dThY-mTXklYe1BP9HKc',
    appId: '1:339553065196:ios:f49d2047cae78fd1156dc9',
    messagingSenderId: '339553065196',
    projectId: 'ceylon-trails-bec69',
    storageBucket: 'ceylon-trails-bec69.firebasestorage.app',
    iosBundleId: 'com.example.ceylonTrails',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpuwgmrgmn6Ib8dThY-mTXklYe1BP9HKc',
    appId: '1:339553065196:ios:f49d2047cae78fd1156dc9',
    messagingSenderId: '339553065196',
    projectId: 'ceylon-trails-bec69',
    storageBucket: 'ceylon-trails-bec69.firebasestorage.app',
    iosBundleId: 'com.example.ceylonTrails',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSILscLjTFgsPYNoTNOddcvOqqQttEgPY',
    appId: '1:339553065196:web:cceb309c8d53d370156dc9',
    messagingSenderId: '339553065196',
    projectId: 'ceylon-trails-bec69',
    authDomain: 'ceylon-trails-bec69.firebaseapp.com',
    storageBucket: 'ceylon-trails-bec69.firebasestorage.app',
    measurementId: 'G-EED7BDTW9B',
  );
}
